# Generated by Django 6.0.6 on 2026-06-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('bio', models.TextField()),
                ('specialities', models.CharField(max_length=200)),
                ('experienceYears', models.IntegerField()),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('dateJoined', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField()),
                ('eventDate', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=60)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.photographer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Portfolio')),
                ('caption', models.CharField(max_length=200)),
                ('uploadedAt', models.DateTimeField(auto_now=True)),
                ('orderId', models.CharField(max_length=60)),
                ('orderStatus', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=60)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paymentMethod', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'Paypal'), ('other', 'Other')], max_length=60)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=60)),
                ('paymentDate', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('reviewDate', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('phoneNo', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='UserProfiles')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoverseapp.user')),
            ],
        ),
    ]
